version: "3.9"
services:
  app:
    build: .
    environment:
      - TASK_NAME
    user: "${DOCKER_USER}"
    volumes:
      - ".:/app:ro"
      - "${TMPDIR}:/tmp"
      - "${STATEDIR}:/state"
      - "../:/task:ro"
    expose:
      - 80
  tor:
    image: goldy/tor-hidden-service:0.3.5.8
    links:
      - app
    environment:
      APP_TOR_SERVICE_HOSTS: 80:app:80
      APP_TOR_SERVICE_VERSION: "3"
      APP_TOR_SERVICE_KEY: ***insert your key here***
