version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - TASK_NAME
    user: "${DOCKER_USER}"
    volumes:
      - "./app:/app:ro"
      - "${TMPDIR}:/tmp"
      - "${STATEDIR}:/state"
      - "./:/task:ro"
  xss:
    build:
      context: .
      dockerfile: Dockerfile.xss
    environment:
      - TASK_NAME
    user: "${DOCKER_USER}"
    volumes:
      - "${TMPDIR}:/tmp"
      - "${STATEDIR}:/state"
      - "./:/task:ro"
networks:
  isolated:
    internal: true
