category: ctb
title:    Стегопентест
points:   100
track:    neutral
author:   baksist
description: >
  <p>[...] Нейронный глаз [...] стегонаграфические свойства [...] логарифм (по основанию 11).</p>
  {{reboot_machine}}
generator: ../_scripts/kyzylborda-lib-generator
daemon:
  exec: ../_scripts/kyzylborda-lib-quarantine-daemon Dockerfile.controller app
  cwd: .
  socket: ./app.sock
  socket_type: http
secrets:
  seed: Zjc5Y2ZkZmMtODM3NC00ZmQ4LTlkYTQt
  flag: ugra_stegano_messages_can_be_dangerous_[a-z0-9]{12}
