FROM python:3-alpine

COPY requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

COPY generator.py /generator.py
COPY secret.json /secret.json

ENTRYPOINT ["python3", "/generator.py", "secret.json"]
