services:
  gitlab:
    image: gitlab/gitlab-ce
    ports:
    - 443:443
    - 80:80
    - 2022:22
    restart: always
    volumes:
    - /var/opt/gitlab/config:/etc/gitlab
    - /var/opt/gitlab/logs:/var/log/gitlab
    - /var/opt/gitlab/data:/var/opt/gitlab
    shm_size: 512mb
    environment:
      GITLAB_OMNIBUS_CONFIG: "external_url 'https://tecret2.o.2023.ugractf.ru/'; gitlab_rails['lfs_enabled'] = false; gitlab_rails['gitlab_shell_ssh_port'] = 2022;"
