category: web
points:   200
title:    The Project O
author:   nsychev
track:    chaotic
depends_on: [or, bururute, noteotp]
description: |
  <pre><code>ARHIV. arhiv!stu!uralni-KOMKIBER!borisov

  10.II.86 UCUCUGA kotoruyu my nadejalis' obuzdat podobno stikhii, okazalas
  nam nepodvlastna, ibo sama zhizn' est' yavleniya, nazyvaemyje nami strogim
  terminom intuitivnaya neodnoznachnost. I stolko axiom i sledstvii ot odnogo
  fakta prirody zagadok...

  K sojaleniu, ja tak bolshe ne mogu. Mi stali tem, chto pitalis ponyat' i
  ustranit'. Okazalos, shto mi sami ucucuga.</code></pre>
generator: ../_scripts/kyzylborda-lib-generator
daemon:
  exec: ../_scripts/kyzylborda-lib-quarantine-daemon Dockerfile.controller app
  cwd: .
  socket: ./app.sock
  socket_type: http
secrets:
  seed: UETNshv5TWrUFA4Dq3t3DdDMva4vPqQqv7GgBhkdb
  flag: ugra_trust_is_the_cornerstone_of_web_[a-z0-9]{16}
